export const FETCHING_LESSONS = 'FETCHING_LESSONS';
export const FETCHED_LESSONS_SUCCESS = 'FETCHED_LESSONS_SUCCESS';
export const FETCHED_LESSONS_FAILURE = 'FETCHED_LESSONS_FAILURE';

//Navigation
export const GO_TO_LESSON = 'GO_TO_LESSON';
export const GO_HOME = 'GO_HOME';